CREATE TABLE COURSE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    DURATION INTEGER NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    COURSE_LEVEL VARCHAR(50) NOT NULL
);

INSERT INTO COURSE(TITLE, DURATION, IS_ACTIVE, COURSE_LEVEL) VALUES ('Java', 30, TRUE, 'BASIC');
INSERT INTO COURSE(TITLE, DURATION, IS_ACTIVE, COURSE_LEVEL) VALUES ('Java', 45, TRUE, 'MEDIUM');
INSERT INTO COURSE(TITLE, DURATION, IS_ACTIVE, COURSE_LEVEL) VALUES ('Java', 60, FALSE, 'ADVANCED');
INSERT INTO COURSE(TITLE, DURATION, IS_ACTIVE, COURSE_LEVEL) VALUES ('Angular 6', 70, TRUE, 'ADVANCED');
INSERT INTO COURSE(TITLE, DURATION, IS_ACTIVE, COURSE_LEVEL) VALUES ('AmazonWS', 30, TRUE, 'ADVANCED');